apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-importer-mysql
spec:
  selector:
    matchLabels:
      app: news-importer-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: news-importer-mysql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: mysql
          image: mysql:5.6
          env:
            - name: MYSQL_USER
              value: silver
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MYSQL_DATABASE
              value: Noticias2011
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql/
---
apiVersion: v1
kind: Service
metadata:
  name: news-importer-mysql
spec:
  selector:
    app: news-importer-mysql
  ports:
    - port: 3306
