apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-importer-rabbitmq
spec:
  selector:
    matchLabels:
      app: news-importer-rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: news-importer-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: sapo
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
          ports:
            - containerPort: 5672
            - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: news-importer-rabbitmq
spec:
  type: NodePort
  selector:
    app: news-importer-rabbitmq
  ports:
    - port: 5672
      name: tcp
    - port: 15672
      name: web
