apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-importer-worker
spec:
  selector:
    matchLabels:
      app: news-importer-worker
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: news-importer-worker
    spec:
      containers:
        - name: news-importer-worker
          image: madsilver/news-importer-worker:1.0.0
          env:
            - name: RABBITMQ_HOST
              value: news-importer-rabbitmq
          command: ["./news-importer-worker"]
          imagePullPolicy: Always

